# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    ahfel:
                        password: $2y$13$mw4oV7NL3genXFJlNSxMf.EwIwkcjBX3DABSWunreulTB0BWpxc9G # pkttoutseul
                        roles: ['ROLE_USER']

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/login$
            anonymous: ~

        secured_area:
            pattern: ^/
            provider: in_memory
            form_login:
                login_path: /login
                check_path: /login_check
                username_parameter: email
                password_parameter: password
                always_use_default_target_path: true
        

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
